### ISSUE TITLE
Revamp Website: v2.0

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/phpid-learning#62]
I feel bored, let's do a fully revamp this website.

What concerns need to address:

- #79 Change CSS to be more clean and professional, Tailwind or BS5 can be an alternative 
- Produce more pages, maybe create a detail page for every session
- Easier static generated, currently w Sapper we do a workaround to generate `tag` pages, if we plan to add detail pages, I just don't think this workaround still applicable. Maybe Next.js can be a candidate for replacement
- #90
- #76
- #78

Figma:

https://www.figma.com/file/qNIg0A9h7PnrFdOVSBbMEH/PHPID-Online-Learning-Redesign?node-id=2%3A2

**Comment by mazipan** [comment]
https://next.docs.astro.build/comparing-astro-vs-other-tools

**Comment by ngekoding** [comment]
How about a feature to filter an event by the speaker?

As we know, some speakers always talking about his/her best knowledge. For example, Mr. Nur Hidayat very well talking about databases, so we can easily get all about databases topic from him without extra searching.

**Comment by mazipan** [comment]
Can you help to create new issue and mention here @ngekoding ?

**Comment by ngekoding** [comment]
Issue created https://github.com/phpid-jakarta/phpid-learning/issues/90

Thanks
